---
env:
  browser: true
  es6: true
  mocha: true
  node: true

extends: airbnb

plugins:
  - react
  - jsx-a11y
  - import

globals:
  request: true
  HOST: true

rules:
  import/no-extraneous-dependencies: 'off'
  import/no-unresolved: 'off'
  import/extensions: 'off'
  no-underscore-dangle: 'off'
  react/forbid-prop-types: 'off'
  class-methods-use-this: 'off'
  react/jsx-no-bind: 'off'
  react/jsx-closing-bracket-location: 'off'