---
env:
  browser: true
  es6: true
  mocha: true
  node: true

extends: airbnb

plugins:
  - react
  - jsx-a11y
  - import

rules:
  import/no-extraneous-dependencies:
    - 2
    - devDependencies: true